# outputs to collect from the rendergan. E.g. fake, tag3d, ...
selected_outputs: "tag3d, fake_without_noise, fake"

# Number of samples of the train set
nb_train_samples: 5e6

# Number of samples of the test set
nb_test_samples: 1e5

epoch: 350
