
# ground truth file
ground_truth: "/mnt/storage/beesbook/datasets/truth_tags.hdf5"

# marks the decoder path
marker: "m"

# augmentation flags: possible values: --noise --augmentation --hist-eq
augmentations: "--noise --augmentation --hist-eq"

# network units
units: 16

# only use sample with a discriminator score greater then this threshold
discriminator_threshold: 0.05

# decoder model type. either resnet or stochastic_wrn
model: stochastic_wrn
