# ground truth validation file
gt_val: "/home/leonsixt/data/gt/data/gt_validation.hdf5"

# ground truth test file
gt_test: "/home/leonsixt/data/gt/data/gt_test.hdf5"

gt_train: "/home/leonsixt/data/gt/data/gt_train_shuffled.hdf5"
gt_train_val: "/home/leonsixt/data/gt/data/gt_train_validation_shuffled.hdf5"
gt_train_test: "/home/leonsixt/data/gt/data/gt_train_test_shuffled.hdf5"


