# number of filters in the last conv layers
# every conv layer before has double the number of filters
units: 32

# number of dense layers before the projection
nb_dense: "1024,1024"

# number of conv layers per resolution
depth: 2

# train this number of epochs
epoch: 500
